source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 8.0.4"
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"
gem "bcrypt", "~> 3.1"
gem "connection_pool", "~> 2.5"
gem "sidekiq", "~> 7.3"
gem "bootsnap", require: false
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "aws-sdk-s3", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
