class StatusPresenter
  LABELS = {
    "PROGRAM_TOTAL_DIFF" => "Есть расхождение между текущей программой и внешним источником",
    "PROGRAM_TOTAL_OK" => "Суммы сходятся",
    "UNASSIGNED_RESIDUAL" => "Служебная или нераспределенная строка Excel",
    "NEEDS_CONFIRMATION" => "Нужно уточнение по документам",
    "POSSIBLE_DOUBLE_COUNT" => "Возможен двойной учет",
    "DOCX_CONTROL_SUM_DIFF" => "Внутренние суммы DOCX не сходятся",
    "MANUAL_INSERT_REQUIRED" => "Нужно выбрать место вставки нового объекта",
    "MATCH_EXACT_CODE" => "Точное совпадение по коду",
    "MATCH_EXACT_NAME" => "Точное совпадение по наименованию",
    "MATCH_FUZZY_CONFIDENT" => "Похожее наименование найдено с высокой уверенностью",
    "MISSING_IN_DOCX" => "Есть во внешнем источнике, нет в текущем дереве программы",
    "draft" => "Черновик",
    "running" => "Выполняется",
    "completed" => "Завершен",
    "needs_confirmation" => "Нужно уточнение",
    "confirmed" => "Агент сопоставил",
    "amount_update" => "Изменение суммы",
    "new_object" => "Новый объект",
    "delete_object" => "Удаление объекта",
    "name_update" => "Изменение наименования",
    "result_update" => "Изменение результата",
    "pending_confirmation" => "Идет сопоставление",
    "ready_for_approval" => "Готово к формированию",
    "approved" => "Готово к формированию",
    "changed" => "Изменена",
    "uploaded_active" => "Активная загруженная редакция",
    "uploaded_inactive" => "Загруженная неактивная редакция",
    "generated_draft" => "Черновик новой редакции",
    "generated_validated" => "Проверенный черновик",
    "generated_rejected" => "Отклоненный черновик",
    "approved_active" => "Утвержденная активная редакция",
    "archived" => "Архивная редакция",
    "applied" => "Применен",
    "export_failed" => "Документ не прошел проверку",
    "needs_manual_review" => "Нужно уточнение",
    "resolved" => "Агент сопоставил",
    "excluded" => "Агент исключил из применения",
    "unresolved" => "В работе у агента",
    "needs_clarification" => "Нужно уточнение: недостаточно данных в документах",
    "valid" => "Документ прошел проверку",
    "valid_with_warnings" => "Документ прошел проверку с предупреждениями",
    "invalid" => "Документ не прошел проверку",
    "rejected" => "Отклонен",
    "queued" => "В очереди",
    "parsing" => "Разбирается",
    "parsed" => "Разобран",
    "failed" => "Ошибка разбора",
    "uploaded" => "Загружен"
  }.freeze

  def self.label(status)
    LABELS.fetch(status.to_s, status.to_s.presence || "Не указано")
  end
end
